In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.3'

In [4]:
a=np.array([1,2,3,4])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
print(a)

[1 2 3 4]


In [7]:
a=np.array([1,2,3,5])

In [8]:
a

array([1, 2, 3, 5])

In [9]:
print(a)

[1 2 3 5]


In [10]:
a.dtype

dtype('int32')

In [11]:
a.ndim

1

In [12]:
a.itemsize

4

In [13]:
a.tolist()

[1, 2, 3, 5]

In [14]:
c=np.array([1,2,3])

In [15]:
c

array([1, 2, 3])

In [16]:
d=np.array([1,2,3])

In [17]:
c is d

False

In [18]:
e = np.asarray(c)

In [19]:
c is e

True

In [20]:
f= c.copy()

In [21]:
f

array([1, 2, 3])

In [22]:
c is f

False

In [23]:
import pandas as pd

In [24]:
pd.__version__

'1.3.4'

In [25]:
s=pd.Series([1,2,3,4], index=list('abcd'))

In [26]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [27]:
s.values

array([1, 2, 3, 4], dtype=int64)

In [28]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [29]:
s.ndim

1

In [31]:
s.shape

(4,)

In [32]:
s.size

4

In [34]:
s.shape

(4,)

In [35]:
s['a']

1

In [36]:
s['d']

4

In [37]:
s['a':'c']

a    1
b    2
c    3
dtype: int64

In [38]:
s[:]

a    1
b    2
c    3
d    4
dtype: int64

In [39]:
s[:-1]

a    1
b    2
c    3
dtype: int64

In [40]:
df=pd.DataFrame([[1,2,3,4],[5,6,7,8]], index=list('ab'), columns=list('abcd'))

In [41]:
df

a  b  c  d
a  1  2  3  4
b  5  6  7  8