In [1]:
import numpy as np

In [2]:
my_list=[0,1,2,3,4,5,6,7,8,9,10]
nparr=np.array(my_list)

In [3]:
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
nparr=np.arange(0,11)
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
nparr_added=nparr+nparr
print(nparr_added)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [6]:
nparr_sub=nparr-nparr
print(nparr_sub)

[0 0 0 0 0 0 0 0 0 0 0]


In [7]:
nparr_mult=nparr*nparr
print(nparr_mult)

[  0   1   4   9  16  25  36  49  64  81 100]


In [9]:
nparr_div=nparr/nparr
print(nparr_div)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-9-abef9bef59eb>:1: RuntimeWarning: invalid value encountered in true_divide
  nparr_div=nparr/nparr


In [10]:
nparr_esc=nparr*10
print(nparr_esc)

[  0  10  20  30  40  50  60  70  80  90 100]


In [11]:
nparr_one_div=1/nparr
print(nparr_one_div)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


<ipython-input-11-6538712cab04>:1: RuntimeWarning: divide by zero encountered in true_divide
  nparr_one_div=1/nparr


In [12]:
nparr_max=np.max(nparr)
print(nparr_max)

10


In [14]:
nparr_min=np.min(nparr)
print(nparr_min)

0


In [15]:
arr_10to50=np.arange(10,51)

In [16]:
print(arr_10to50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [17]:
arr_10to50_even=np.arange(10,51,2)
print(arr_10to50_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [19]:
np.arange(1,10).reshape(3,3)#행,열

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.random.rand(1)

array([0.57583234])

In [21]:
np.random.randn(25)

array([-0.94888208,  1.0521493 ,  0.82041709, -0.58488245, -1.03781277,
        0.14148325, -0.31521542, -0.65247422, -0.61638939,  0.78335398,
       -0.21510678, -1.08683477, -0.5192688 , -1.92565954,  1.21584859,
       -1.66749132, -1.24567072, -0.0424426 , -0.54372623, -1.20664505,
       -1.87824252,  0.83871997, -0.95845958, -1.87185598, -0.59629292])

In [27]:
np.arange(1,101).reshape(10,10)*2

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100],
       [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
       [122, 124, 126, 128, 130, 132, 134, 136, 138, 140],
       [142, 144, 146, 148, 150, 152, 154, 156, 158, 160],
       [162, 164, 166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196, 198, 200]])

In [23]:
arr_2_d=np.arange(1,26).reshape(5,5)
print(arr_2_d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [25]:
arr_2_d[3,0]

16

In [26]:
arr_2_d[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [28]:
arr_2_d[4,:]

array([21, 22, 23, 24, 25])

In [29]:
np.sum(arr_2_d)

325

In [36]:
np.std(arr_2_d)#표준편차

7.211102550927978

In [37]:
arr_2_d.std()

7.211102550927978

In [40]:
arr_2_d.sum(axis=0)#열의 더한 값
# axis=0 -> row -> so the result is placed in a row
# (then it is a columns' sum)
# axis=1 -> columns -> so the result is placed in a column 
# (then it is a row's sum:)

array([55, 60, 65, 70, 75])

In [41]:
arr_2_d.sum(axis=1)#행의 더한 값

array([ 15,  40,  65,  90, 115])